"""Extended AWS behavioral usage models for observability, analytics, and hosting services."""

from __future__ import annotations

from app.pricing.usage.behavioral_models import ServiceBehavioralModel, _float_input

_AMPLIFY_BEHAVIORAL = ServiceBehavioralModel(
    service="Amplify",
    behavioral_inputs=(
        _float_input(
            "sessions_per_user_per_month",
            "App sessions driving hosting requests per user per month.",
            "sessions/user/month",
            min_value=0.1,
            max_value=120,
        ),
        _float_input(
            "requests_per_session",
            "Hosting/SSR requests one user generates per session.",
            "requests/session",
            min_value=1,
            max_value=500,
        ),
    ),
    config_input_keys=frozenset({"build_minutes_per_month"}),
)

_AMPLIFY_HOSTING_BEHAVIORAL = ServiceBehavioralModel(
    service="Amplify Hosting",
    behavioral_inputs=_AMPLIFY_BEHAVIORAL.behavioral_inputs,
    config_input_keys=frozenset({"build_minutes_per_month"}),
)

_BEDROCK_BEHAVIORAL = ServiceBehavioralModel(
    service="Bedrock",
    behavioral_inputs=(
        _float_input(
            "ai_calls_per_user_per_month",
            "Generative AI invocations one user triggers per month.",
            "calls/user/month",
            min_value=0,
            max_value=10_000,
        ),
        _float_input(
            "avg_input_tokens_per_call",
            "Average input tokens per Bedrock invocation.",
            "tokens/call",
            min_value=1,
            max_value=100_000,
        ),
        _float_input(
            "avg_output_tokens_per_call",
            "Average output tokens per Bedrock invocation.",
            "tokens/call",
            min_value=0,
            max_value=100_000,
        ),
    ),
    config_input_keys=frozenset(),
)

_ELASTICACHE_BEHAVIORAL = ServiceBehavioralModel(
    service="ElastiCache",
    behavioral_inputs=(),
    config_input_keys=frozenset({"node_type", "hours_per_month"}),
)

_OPENSEARCH_BEHAVIORAL = ServiceBehavioralModel(
    service="OpenSearch Service",
    behavioral_inputs=(
        _float_input(
            "index_operations_per_user_per_month",
            "Search index writes/updates attributable to one user per month.",
            "ops/user/month",
            min_value=0,
            max_value=10_000,
        ),
        _float_input(
            "search_queries_per_user_per_month",
            "Search queries one user runs per month.",
            "queries/user/month",
            min_value=0,
            max_value=10_000,
        ),
    ),
    config_input_keys=frozenset(),
)

_ATHENA_BEHAVIORAL = ServiceBehavioralModel(
    service="Athena",
    behavioral_inputs=(
        _float_input(
            "analytics_queries_per_user_per_month",
            "Ad-hoc analytics queries one user runs per month.",
            "queries/user/month",
            min_value=0,
            max_value=1_000,
        ),
        _float_input(
            "avg_tb_scanned_per_query",
            "Average terabytes scanned per Athena query.",
            "TB/query",
            min_value=0.0001,
            max_value=100,
        ),
    ),
    config_input_keys=frozenset(),
)

_QUICKSIGHT_BEHAVIORAL = ServiceBehavioralModel(
    service="QuickSight",
    behavioral_inputs=(),
    config_input_keys=frozenset({"reader_seats", "author_seats"}),
)

_SES_BEHAVIORAL = ServiceBehavioralModel(
    service="SES",
    behavioral_inputs=(
        _float_input(
            "emails_per_user_per_month",
            "Transactional emails sent to one user per month.",
            "emails/user/month",
            min_value=0,
            max_value=100,
        ),
    ),
    config_input_keys=frozenset(),
)

_CLOUDWATCH_BEHAVIORAL = ServiceBehavioralModel(
    service="CloudWatch",
    behavioral_inputs=(
        _float_input(
            "api_calls_per_user_per_month",
            "Monitoring API calls attributable to one user per month.",
            "calls/user/month",
            min_value=0,
            max_value=10_000,
        ),
    ),
    config_input_keys=frozenset({"custom_metrics_count"}),
)

_CLOUDWATCH_LOGS_BEHAVIORAL = ServiceBehavioralModel(
    service="CloudWatch Logs",
    behavioral_inputs=(
        _float_input(
            "log_events_per_user_per_month",
            "Log events generated by one user per month.",
            "events/user/month",
            min_value=0,
            max_value=100_000,
        ),
        _float_input(
            "avg_log_event_kb",
            "Average log event payload size.",
            "KB/event",
            min_value=0.01,
            max_value=64,
        ),
    ),
    config_input_keys=frozenset(),
)

_CLOUDWATCH_DASHBOARDS_BEHAVIORAL = ServiceBehavioralModel(
    service="CloudWatch Dashboards",
    behavioral_inputs=(),
    config_input_keys=frozenset({"dashboard_count", "hours_per_month"}),
)

_CLOUDWATCH_ALARMS_BEHAVIORAL = ServiceBehavioralModel(
    service="CloudWatch Alarms",
    behavioral_inputs=(),
    config_input_keys=frozenset({"standard_alarms_count", "hours_per_month"}),
)

_SSM_BEHAVIORAL = ServiceBehavioralModel(
    service="SSM Parameter Store",
    behavioral_inputs=(
        _float_input(
            "config_reads_per_user_per_month",
            "Parameter reads attributable to one user per month.",
            "reads/user/month",
            min_value=0,
            max_value=10_000,
        ),
    ),
    config_input_keys=frozenset({"parameters_count"}),
)

_APPCONFIG_BEHAVIORAL = ServiceBehavioralModel(
    service="AppConfig",
    behavioral_inputs=(),
    config_input_keys=frozenset({"configurations_count", "deployment_events_per_month"}),
)

_XRAY_BEHAVIORAL = ServiceBehavioralModel(
    service="X-Ray",
    behavioral_inputs=(
        _float_input(
            "traced_requests_per_user_per_month",
            "Sampled traced requests attributable to one user per month.",
            "traces/user/month",
            min_value=0,
            max_value=10_000,
        ),
    ),
    config_input_keys=frozenset(),
)

EXTENDED_AWS_BEHAVIORAL_MODELS: dict[str, ServiceBehavioralModel] = {
    model.service: model
    for model in (
        _AMPLIFY_BEHAVIORAL,
        _AMPLIFY_HOSTING_BEHAVIORAL,
        _BEDROCK_BEHAVIORAL,
        _ELASTICACHE_BEHAVIORAL,
        _OPENSEARCH_BEHAVIORAL,
        _ATHENA_BEHAVIORAL,
        _QUICKSIGHT_BEHAVIORAL,
        _SES_BEHAVIORAL,
        _CLOUDWATCH_BEHAVIORAL,
        _CLOUDWATCH_LOGS_BEHAVIORAL,
        _CLOUDWATCH_DASHBOARDS_BEHAVIORAL,
        _CLOUDWATCH_ALARMS_BEHAVIORAL,
        _SSM_BEHAVIORAL,
        _APPCONFIG_BEHAVIORAL,
        _XRAY_BEHAVIORAL,
    )
}
