"""Cloud-agnostic behavioral models keyed by architecture component type."""

from __future__ import annotations

from app.pricing.usage.behavioral_models import ServiceBehavioralModel, _float_input, _int_input

_WEB_APP = ServiceBehavioralModel(
    service="__web_app__",
    behavioral_inputs=(
        _float_input(
            "sessions_per_user_per_month",
            "How often one user loads the web app per month.",
            "sessions/user/month",
            min_value=0.1,
            max_value=120,
        ),
        _float_input(
            "requests_per_session",
            "HTTP/API requests one user generates per session.",
            "requests/session",
            min_value=1,
            max_value=200,
        ),
        _float_input(
            "avg_response_size_kb",
            "Average outbound payload size per request.",
            "KB/request",
            min_value=0.1,
            max_value=10_240,
        ),
    ),
    config_input_keys=frozenset({"build_minutes_per_month", "instance_hours_per_month"}),
)

_API_GATEWAY = ServiceBehavioralModel(
    service="__api_gateway__",
    behavioral_inputs=(
        _float_input(
            "sessions_per_user_per_month",
            "How often one user triggers API gateway traffic per month.",
            "sessions/user/month",
            min_value=0.1,
            max_value=120,
        ),
        _float_input(
            "requests_per_session",
            "API requests one user generates per session.",
            "requests/session",
            min_value=1,
            max_value=500,
        ),
        _float_input(
            "avg_response_size_kb",
            "Average outbound response size per API request.",
            "KB/request",
            min_value=0.1,
            max_value=10_240,
        ),
    ),
    config_input_keys=frozenset({"sku_tier", "api_type"}),
)

_DATABASE = ServiceBehavioralModel(
    service="__database__",
    behavioral_inputs=(
        _float_input(
            "reads_per_user_per_month",
            "Read/query operations one user performs per month.",
            "reads/user/month",
            min_value=0,
            max_value=50_000,
        ),
        _float_input(
            "writes_per_user_per_month",
            "Write/update operations one user performs per month.",
            "writes/user/month",
            min_value=0,
            max_value=10_000,
        ),
        _float_input(
            "storage_kb_per_user",
            "Stored data attributable to one user.",
            "KB/user",
            min_value=0,
            max_value=10_240,
        ),
    ),
    config_input_keys=frozenset(),
)

_NOTIFICATION = ServiceBehavioralModel(
    service="__notification__",
    behavioral_inputs=(
        _float_input(
            "messages_per_user_per_month",
            "Push/email/SMS notifications one user receives per month.",
            "messages/user/month",
            min_value=0,
            max_value=500,
        ),
        _float_input(
            "avg_message_size_kb",
            "Average payload size per notification.",
            "KB/message",
            min_value=0.01,
            max_value=1024,
        ),
    ),
    config_input_keys=frozenset({"namespace_hours_per_month"}),
)

_MONITORING = ServiceBehavioralModel(
    service="__monitoring__",
    behavioral_inputs=(
        _float_input(
            "api_calls_per_user_per_month",
            "Monitoring/metrics API calls attributable to one user per month.",
            "calls/user/month",
            min_value=0,
            max_value=1000,
        ),
    ),
    config_input_keys=frozenset(
        {"custom_metrics_count", "alert_rules_count", "alert_policies_count"}
    ),
)

_LOGGING = ServiceBehavioralModel(
    service="__logging__",
    behavioral_inputs=(
        _float_input(
            "log_events_per_user_per_month",
            "Log events generated by one user per month.",
            "events/user/month",
            min_value=0,
            max_value=50_000,
        ),
        _float_input(
            "avg_log_event_kb",
            "Average log event size.",
            "KB/event",
            min_value=0.01,
            max_value=64,
        ),
    ),
    config_input_keys=frozenset(),
)

_CONFIG = ServiceBehavioralModel(
    service="__config__",
    behavioral_inputs=(
        _float_input(
            "config_reads_per_user_per_month",
            "Configuration/secret read operations per user per month.",
            "reads/user/month",
            min_value=0,
            max_value=500,
        ),
    ),
    config_input_keys=frozenset(
        {
            "configuration_stores",
            "configurations_count",
            "secrets_count",
            "deployment_events_per_month",
        }
    ),
)

_API_SERVICE = ServiceBehavioralModel(
    service="__api_service__",
    behavioral_inputs=(
        _float_input(
            "sessions_per_user_per_month",
            "How often one user triggers backend flows per month.",
            "sessions/user/month",
            min_value=0.1,
            max_value=120,
        ),
        _float_input(
            "invocations_per_session",
            "Backend invocations one user triggers per session.",
            "invocations/session",
            min_value=1,
            max_value=500,
        ),
        _float_input(
            "avg_response_size_kb",
            "Average outbound payload per invocation.",
            "KB/invocation",
            min_value=0.1,
            max_value=10_240,
        ),
    ),
    config_input_keys=frozenset(
        {
            "plan",
            "avg_execution_duration_ms",
            "memory_mb",
            "cpu",
            "memory_gb",
            "min_replicas",
            "max_replicas",
        }
    ),
)

_OBJECT_STORAGE = ServiceBehavioralModel(
    service="__object_storage__",
    behavioral_inputs=(),
    config_input_keys=frozenset(
        {"access_tier", "redundancy", "list_operations", "static_storage_gb"}
    ),
)

_CDN = ServiceBehavioralModel(
    service="__cdn__",
    behavioral_inputs=(
        _float_input(
            "page_views_per_user_per_month",
            "Static asset page views per user per month.",
            "views/user/month",
            min_value=0,
            max_value=500,
        ),
        _float_input(
            "avg_object_size_kb",
            "Average CDN asset size per view.",
            "KB/view",
            min_value=1,
            max_value=5120,
        ),
    ),
    config_input_keys=frozenset(),
)

_AI = ServiceBehavioralModel(
    service="__ai__",
    behavioral_inputs=(
        _float_input(
            "ai_calls_per_user_per_month",
            "AI/LLM calls one user makes per month.",
            "calls/user/month",
            min_value=0,
            max_value=10_000,
        ),
        _int_input(
            "avg_input_tokens_per_call",
            "Average input tokens per AI call.",
            "tokens/call",
            min_value=0,
            max_value=100_000,
        ),
        _int_input(
            "avg_output_tokens_per_call",
            "Average output tokens per AI call.",
            "tokens/call",
            min_value=0,
            max_value=50_000,
        ),
    ),
    config_input_keys=frozenset(),
)

_COMPONENT_TYPE_ALIASES: dict[str, str] = {
    "admin_panel": "web_app",
    "mobile_app": "web_app",
    "service": "api_service",
    "api": "api_service",
    "worker": "api_service",
    "queue_worker": "api_service",
    "secrets": "config",
    "cache": "config",
    "load_balancer": "api_gateway",
    "search": "database",
    "analytics": "monitoring",
}

_COMPONENT_TYPE_BEHAVIORAL_MODELS: dict[str, ServiceBehavioralModel] = {
    "web_app": _WEB_APP,
    "api_gateway": _API_GATEWAY,
    "database": _DATABASE,
    "notification": _NOTIFICATION,
    "monitoring": _MONITORING,
    "logging": _LOGGING,
    "config": _CONFIG,
    "api_service": _API_SERVICE,
    "object_storage": _OBJECT_STORAGE,
    "cdn": _CDN,
    "ai_provider": _AI,
}


def normalize_component_type(component_type: str) -> str:
    normalized = component_type.strip().lower()
    return _COMPONENT_TYPE_ALIASES.get(normalized, normalized)


def get_component_type_behavioral_model(component_type: str) -> ServiceBehavioralModel | None:
    normalized = normalize_component_type(component_type)
    return _COMPONENT_TYPE_BEHAVIORAL_MODELS.get(normalized)
